### ISSUE TITLE
Better rate limit without relying on magic numbers of sleep

### ISSUE THREAD

**Issue by shnwnd** [codeforatlanta/csv_geocoder#1]
Would this provide a better ratelimit? https://github.com/stungeye/glutton_ratelimit

**Comment by shnwnd** [comment]
Why was this closed without a comment?

Google rate limits requests to 5 per second. I think a delay = 0.21 is close but does not deal with different speeds of requests.

**Comment by sb8244** [comment]
Not advocating for anything here, but what is the use case you are having problem with?
